# wrangler.toml
name = "astro-paper-sanity"
compatibility_date = "2025-05-03"
account_id = "6c09e3bab91aa41c1bcb2f22c6dcf9cd"
type="javascript"

[site]
  bucket = "./dist"
  entry-point = "."

[functions]
  directory = "./functions/api"