export const defaultSiteConfig = {
  website: "your_site_url",
  author: "your_name",
  profile: "https://your_site_url/",
  email: "mail@example.com",
  description: "your_description",
  twitter: "https://twitter.com/your_twitter",
  github: "https://github.com/your_github",
  title: "your_site_title",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 5,
  postPerPage: 5,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  dynamicOgImage: true,
  lang: "ja",
  timezone: "Asia/Tokyo",
} as const;