export const defaultSiteConfig = {
  website: "https://astro-paper-sanity.vercel.app/",
  author: "Nadja",
  profile: "https://astro-paper-sanity.vercel.app/",
  email: "mail@nadja.jp",
  description: "AstroPaper Sanity Sample Site",
  twitter: "https://twitter.com/your_twitter",
  github: "https://github.com/NadjaSenpai/astro-paper-sanity",
  title: "AstroPaper Sanity",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 5,
  postPerPage: 5,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  dynamicOgImage: true,
  lang: "ja",
  timezone: "Asia/Tokyo",
} as const;