export const defaultSiteConfig = {
  website: "https://example.com/",
  author: "Your Name",
  profile: "https://example.com/",
  email: "hello@example.com",
  description: "An Astro + Sanity blog starter",
  twitter: "https://twitter.com/your_handle",
  github: "https://github.com/your_user/your_repo",
  title: "Astro Paper Sanity",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 5,
  postPerPage: 5,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  dynamicOgImage: true,
  lang: "ja",
  timezone: "Asia/Tokyo",
} as const;
